### ISSUE TITLE
It doesent work. PLEASE HELP

### ISSUE THREAD

**Issue by SSMcTiny** [HAHAYOUDEAD/NorthfolkClothingPack#1]
I've tried everything, doesent work no matter what i do.

**Comment by HAHAYOUDEAD** [comment]
What exactly did you do step-by-step, and how exactly does it not work? Does it show up in MelonLoader?

It would be better if you went to TLD modding discord, we have a bot there to help identify the problem: https://discord.gg/Chq4yEFx

**Comment by SSMcTiny** [comment]
it doesent show up in the melonloader, how do i install it propperly?

**Comment by HAHAYOUDEAD** [comment]
So you're saying you tried everything yet you didn't try reading installation instructions? ;) You have to install ModComponent first(read it's installation instuctions, it has some dependencies). After you've done that, get my mod from releases page and place it into Mods folder

**Comment by HAHAYOUDEAD** [comment]
I assume it's working now?

**Comment by SSMcTiny** [comment]
not yet

**Comment by SSMcTiny** [comment]
So do i just place the "NorthfolkClothingPack" folder into the mods?

**Comment by HAHAYOUDEAD** [comment]
what folder? Go to releases page and get the .modcomponent file

**Comment by SSMcTiny** [comment]
Thanks man, turns out im just retarded.
