### ISSUE TITLE
Craftable Items not showing in blueprints

### ISSUE THREAD

**Issue by spencerjustin** [HAHAYOUDEAD/NorthfolkClothingPack#5]
Not sure if this is the right place to report this, but this mod is not working for me. The items are not showing up in the blueprints area to craft.
Not sure what Info you need, if any.
Running Mod Components. Have taken out all other mods to see if there was a conflict, nope, still not working. Updated Steam copy with DLC.

**Comment by HAHAYOUDEAD** [comment]
go to our modding discord and send your log into #troubleshooting, that way me or some other modders can see what's wrong and help you fix it
https://discord.gg/EktcYFwh
