### ISSUE TITLE
Unable to craft Wolfskin hat or boots

### ISSUE THREAD

**Issue by Silveressa** [HAHAYOUDEAD/NorthfolkClothingPack#8]
Despite having all the needed materials it refuses to craft either item, clicking on the crafting button to start crafting, but nothing happens.

Even attempting to add the Wolfskinboots and Wolfskinhat via the dev console doesn't work.

**Comment by HAHAYOUDEAD** [comment]
do you have latest versions of ModComponent and its dependencies? there's no code in my mod, so if something isn't working - it's most likely because of ModComponent, be sure to update it

**Comment by Silveressa** [comment]
Thanks, turns out it was a dependency for ModComponent (Gear Spawner) that was out of date and keeping things from working as intended. After updating it everything is working 100% once more, cheers!
